---
# The name of your system
title: "Euterpe"
subtitle: "An AI music interaction system framework"

# Set the correct flags based on the type of your music interaction algorithm
# Any combination is valid
noteBasedMode: 
  # If eventBased: true, then the worker's processNoteEvent() hook is active
  # for instant processing of each user's MIDI event.
  eventBased: true
  # If clockBased: true, then the worker's processClockEvent() hook is active
  # for processing raw and quantized MIDI events buffers at every "clock-tick"
  # If clockBased = false, the processClockEvent() is not active, but we still
  # create a clock to "power" the scrolling functionality of the PianoRoll and Score UIs
  clockBased: true

# If audioBasedMode = true, the worker's processAudioBuffer() hook is active.
audioBasedMode: false

# The settings for the clockBased operation.
# These are taken into account only if clockBased: true
clockBasedSettings:
  ticksPerBeat: 4 # use that for 16th-note grid on 4/4
  timeSignature:
    numerator: 4
    denominator: 4
  # BPM. tempo + ticksPerBeat are used to determine the clockPeriod
  # This is just the default value. The user can later change it
  # from the settings menu (effectively changing the clock's period)
  tempo: 120
  # Set the clockPeriod explicitly (milliseconds)
  # if used, the ticksPerBeat, timeSignature and tempo are ignored
  # Use only if your music interaction algorithm
  # operates on a "free-time" mode (no BPM or timeSignature)
  clockPeriod: null
  # Choose what information you want Euterpe to provide to your algorithm (Worker)
  # at every clock-tick
  eventBuffer: false # A buffer with all the MIDI events played by the user since the last tick
  quantizedEvents: true # Only the quantized MIDI events that correspond to the current tick. 
    
# Set the polyphony that your music algorithm supports. Euterpe limits the user's input polyphony
# so that you don't have to do it. Currently, it only applies to the quantizedEvents (clockBased mode)
polyphony:
  input: 1
  output: 1

# Worker related settings.
workerSettings:
  # For Workers that require warmup (such as neural networks)
  warmupRounds: 100
  # Many music interaction algorithms support controlling their output randomness 
  # (e.g., sampling temperature).
  # Default value for randomness(stochasticity) is 0, and is controlled by a slider
  # within the settings tab. (max=1)
  randomness: 0

# Choose the text to be displayed in the splash screen animation
introModal: false
introModalContent:
  - "Hi! This is Euterpe."
  - "I am a web-framework for music interaction systems."

gui:
  score: false