players:
  human:
    label: 'User' # player labels must be unique
    mute: false
    volume: 5
    instruments: 
        # it must be one of the available instrument ids in audio/samples
        # you can't have two instruments with the same id in the same player 
      - id: "piano" 
        label: "Piano" # can be anything
        mute: false
        volume: 5
        default: true
      - id: "synth"
        label: "Synth"
        mute: false
        volume: 6
  worker:
    label: 'Worker'
    mute: false
    volume: 5
    instruments:
      - id: "piano"
        label: "Piano"
        mute: false
        volume: 7
        default: true
      - id: "synth"
        label: "Synth"
        mute: false
        volume: 8
      - id: "drums"
        label: "Drums"
        mute: false
        volume: 9
      - id: "upright_bass"
        label: "Bass"
        mute: false
        volume: 10
  metronome:
    label: 'Metronome'
    mute: true
    volume: 5
    instruments:
      - id: "click"
        label: "Click"
        mute: true
        volume: 5