instruments:
  human: 
    - id: 1
      name: "Piano"
      mute: false
      volume: 5
      default: true
    - id: 2
      name: "Synth"
      mute: false
      volume: 6
  worker:
    - id: 1
      name: "Piano"
      mute: false
      volume: 7
    - id: 2
      name: "Synth"
      mute: false
      volume: 8
    - id: 3
      name: "Drums"
      mute: false
      volume: 9
    - id: 4
      name: "Bass"
      mute: false
      volume: 10
  metronome:
    - id: 1
      name: "Metronome"
      mute: true
      volume: 5