gui:
  score: false
  textBox:
    title: "Chord"
  monitor:
    title: "Monitor"
    variables:
      - id: 1
        label: "Variable 1"
        graph:
          min: 0
          max: 1

      
  settings:
    switches:
      - id: 1
        label: "Switch 1"
        status: false
      - id: 2
        label: "Switch 2"
        status: false
      - id: 3
        label: "Switch 3"
        status: false
      - id: 4
        label: "Switch 4"
        status: false

    sliders:
      - id: 1
        label: "Slider 1"
        value: 0
        min: 0
        max: 100
      - id: 2
        label: "Slider 2"
        value: 0
        min: 0
        max: 100
      - id: 3
        label: "Slider 3"
        value: 0
        min: 0
        max: 100
      - id: 4
        label: "Slider 4"
        value: 0
        min: 0
        max: 100

    buttons:
      - id: 1
        label: "Button 1"
      - id: 2
        label: "Button 2"
      - id: 3
        label: "Button 3"
      - id: 4
        label: "Button 4"




