gui:
  score: 
    status: true
  textBox:
    status: true
    title: "Chord"
  pianoRoll:
    status: true
    human: true
    agent: true
  keyboard:
    status: true
    octaveStart: 2
    octaveEnd: 6
  chromaChart:
    status: true
  audioMeter: 
    status: true
  monitor:
    status: true
    title: "Monitor"
    structure:
      - label: "Audio levels"
        parameters:
          - id: 0 
            label: "rms" 
            interval: 50
            graph: true
            min: 0
            max: 0.2
      - label: "Agent"
        parameters:
          - id: 3
            label: "Debug"
            interval: 100 
            graph: true
            min: 80
            max: 130